[tool.poetry]
name = "falinks"
version = "0.1.0"
description = ""
authors = ["Patrik Chytil <patrikch@centrum.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
